### ISSUE TITLE
Having trouble with the plugin.

### ISSUE THREAD

**Issue by Jxyrod22** [GeorgH93/Bukkit_Minepacks#1]
I gave permissions to the ranks who I want to use it but none of them are able to execute the commands. It just says no permission when they try the command to open the backpack when I gave the correct permission nodes too. I'm running minecraft 1.7.10 and using the PEX as my permission group.

**Comment by GeorgH93** [comment]
Can you please give me more details. PEX version? Config? Online / Offline mode?
